name: Java Gradle Project Build and Upload

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: https://github.com/qinjunhaocn/LunaGC_5.0.0.git
        ref: main
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Change directory and make gradlew executable
      run: |
        cd LunaGC_5.0.0
        chmod +x gradlew

    - name: Build with Gradle
      working-directory: ./LunaGC_5.0.0
      run: ./gradlew jar

    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: LunaGC-Jar
        path: ./LunaGC_5.0.0/build/libs/*.jar
